name: Deploy to Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image to ECR
        run: |
          REPO_URI=${{ secrets.AWS_ECR_REPO_URI }}
          docker build -t $REPO_URI:latest .
          docker push $REPO_URI:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/cookiemaps || exit 1
            echo "${{ secrets.ENV_FILE }}" > .env
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO_URI }}
            docker pull ${{ secrets.AWS_ECR_REPO_URI }}:latest
            docker stop cookiemaps || true
            docker rm cookiemaps || true
            docker run -d --name cookiemaps --env-file .env -p 8000:8000 ${{ secrets.AWS_ECR_REPO_URI }}:latest 
